FROM node:10.9 AS node
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base

FROM build
RUN ls -la
RUN dotnet restore "./Source/BB.API/BB.API.csproj"
RUN dotnet build "./Source/BB.API/BB.API.csproj" -c Release

FROM node 
WORKDIR /Beyond-Biblical/Source/BB.UI
RUN npm install && npm run build

FROM build AS publish
WORKDIR /Beyond-Biblical
RUN dotnet publish "./Source/BB.API/BB.API.csproj" -c Release -o /app/publish

FROM base
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_URLS=http://+:80

FROM base AS final
WORKDIR /app
COPY /Source/BB.UI/dist/* app/publish/wwwroot
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BB.API.dll"]