FROM node:17.8.0 AS node
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base

FROM build as build-api
WORKDIR /app
COPY * ./Source/
RUN mv ./Source/GlobalSuppressions.cs ./
RUN dotnet restore "Source/BB.API/BB.API.csproj"
RUN dotnet publish "Source/BB.API/BB.API.csproj" -c Release -o ./publish

FROM node AS build-ui
WORKDIR /app
COPY * ./
RUN cd BB.UI && npm install && npm run build

FROM base AS host
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_URLS=http://+:80
COPY --from=build-ui /app/BB.UI/dist/* ./wwwroot/
COPY --from=build-api /app/publish/* ./
ENTRYPOINT ["dotnet", "BB.API.dll"]