version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    executor: windows/default
    steps:
      - checkout
      - run:
          name: "Install API dependencies"
          command: dotnet restore .\Source\BB.API\BB.API.csproj
      - run:
          name: "Build Tests"
          command: ForEach ($folder in (Get-ChildItem -Path Tests -Directory)) { dotnet build $folder.FullName }
      - run:
          name: "Run Tests"
          command: ForEach ($folder in (Get-ChildItem -Path Tests -Directory)) { dotnet test $folder.FullName }
  deploy:
    docker:
      - image: cimg/go:1.17
        auth:
          username: airistotal
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t airistotal/beyond-biblical:$TAG --file .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push airistotal/beyond-biblical:$TAG

workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy