version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - run:
          name: "Install API dependencies"
          command: dotnet restore .\Source\BB.API\BB.API.csproj
      - run:
          name: "Build API"
          command: dotnet publish .\Source\BB.API\BB.API.csproj -c Release
      - run:
          name: "Install UI dependencies"
          command: cd ".\Source\BB.UI"; npm install
      - run:
          name: "Build UI"
          command: cd ".\Source\BB.UI"; npm run build
      - run:
          name: "Create wwwroot folder"
          command: New-Item -Path ".\Source\BB.API\bin\Release\netcoreapp3.0\publish\" -Name "wwwroot" -ItemType "directory"
      - run:
          name: "Clean and Copy UI to publish folder"
          command: Copy-Item -Path ".\Source\BB.API\wwwroot\*" -Destination ".\Source\BB.API\bin\Release\netcoreapp3.0\publish\wwwroot" -Recurse
      - store_artifacts:
          path: .\Source\BB.API\bin\Release\netcoreapp3.0\publish\