version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    executor: windows/default
    steps:
      - checkout
      - run:
          name: "Install API dependencies"
          command: dotnet restore .\Source\BB.API\BB.API.csproj
      - run:
          name: "Build API"
          command: dotnet build .\Source\BB.API\BB.API.csproj
      - run:
          name: "Build Tests"
          command: ForEach ($folder in (Get-ChildItem -Path Tests -Directory)) { dotnet build $folder.FullName }
      - run:
          name: "Run Tests"
          command: ForEach ($folder in (Get-ChildItem -Path Tests -Directory)) { dotnet test $folder.FullName }
      - run:
          name: "Install UI dependencies"
          command: cd ".\Source\BB.UI"; npm install
      - run:
          name: "Build UI"
          command: cd ".\Source\BB.UI"; npm run build
      - run:
          name: "Create wwwroot folder"
          command: New-Item -Path ".\Source\BB.API\bin\Release\netcoreapp3.0\publish\" -Name "wwwroot" -ItemType "directory"
      - run:
          name: "Clean and Copy UI to publish folder"
          command: Copy-Item -Path ".\Source\BB.UI\dist\*" -Destination ".\Source\BB.API\bin\Release\netcoreapp3.0\publish\wwwroot" -Recurse
      - persist_to_workspace:
          root: .
          paths:
            - .\Source\BB.API\bin\Release\netcoreapp3.0\publish
      - store_artifacts:
          path: .\Source\BB.API\bin\Release\netcoreapp3.0\publish

workflows:
  version: 2
  build:
    jobs:
      - build