version: 2.1

orbs:
  win: circleci/windows@1.0.0
  aws-cli: circleci/aws-cli@0.1.4

jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - run:
          name: "Install API dependencies"
          command: dotnet restore .\Source\BB.API\BB.API.csproj
      - run:
          name: "Build API"
          command: dotnet publish .\Source\BB.API\BB.API.csproj -c Release
      - run:
          name: "Build Tests"
          command: ForEach ($folder in (Get-ChildItem -Path Tests -Directory)) { dotnet build $folder.FullName }
      - run:
          name: "Run Tests"
          command: ForEach ($folder in (Get-ChildItem -Path Tests -Directory)) { dotnet test $folder.FullName }
      - run:
          name: "Install UI dependencies"
          command: cd ".\Source\BB.UI"; npm install
      - run:
          name: "Build UI"
          command: cd ".\Source\BB.UI"; npm run build
      - run:
          name: "Create wwwroot folder"
          command: New-Item -Path ".\Source\BB.API\bin\Release\netcoreapp3.0\publish\" -Name "wwwroot" -ItemType "directory"
      - run:
          name: "Clean and Copy UI to publish folder"
          command: Copy-Item -Path ".\Source\BB.API\wwwroot\*" -Destination ".\Source\BB.API\bin\Release\netcoreapp3.0\publish\wwwroot" -Recurse
      - persist_to_workspace:
          root: .
          paths:
            - .\Source\BB.API\bin\Release\netcoreapp3.0\publish
            - .\Source\BB.API\bin\Release\netcoreapp3.0\publish
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Over SSH
          command: scp -r ./Source/BB.API/bin/Release/netcoreapp3.0/publish Administrator@3.17.39.158:/inetpub/BB

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master